import { Navbar } from "@/components/layouts";
import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className="h-screen flex-col">
      <Head>
        <title>Exchange App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex-grow p-4">
        <div className="mx-auto max-w-7xl p-3">
          <Component {...pageProps} />
        </div>
      </main>
    </div>
  );
}
